# -*- coding: utf-8 -*-
"""ANN IRIS MULTICLASS CLASSIFICATION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CbZh8PAdWEHrrvYu37MRRNlZxH27J2at
"""

# import all necessary library
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
import keras
from keras.models import Sequential
from keras.layers import Dense

#load data from sklearn.datasets
data=load_iris()
X=data.data
y=data.target

#lets find what are the category of plant which we want to classify
print(data.target_names)
#there are three class and its example of mulitclass classification
#['setosa' 'versicolor' 'virginica']

#shape of X
X.shape

#Target array from
Y=pd.get_dummies(y).values

#split data into train and testing dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=42)

#lets form model for multiclass calss classification
#lets make model from keras
model=Sequential()
#lets form 1st hidden layer
model.add(Dense(4,input_shape=(4,),activation='relu',kernel_initializer='glorot_uniform'))
#output layer
model.add(Dense(3,activation='softmax',kernel_initializer='glorot_uniform'))

#compile our model
model.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

#model fit and train training dataset
model.fit(x_train,y_train,batch_size=10,epochs=150)
#training phase
'''


Epoch 1/150
11/11 [==============================] - 0s 1ms/step - loss: 3.1949 - accuracy: 0.6381
Epoch 2/150
11/11 [==============================] - 0s 1ms/step - loss: 2.9207 - accuracy: 0.6381
Epoch 3/150
11/11 [==============================] - 0s 1ms/step - loss: 2.6637 - accuracy: 0.5619
Epoch 4/150
11/11 [==============================] - 0s 1ms/step - loss: 2.3875 - accuracy: 0.5524
Epoch 5/150
11/11 [==============================] - 0s 1ms/step - loss: 2.1538 - accuracy: 0.5333
Epoch 6/150
11/11 [==============================] - 0s 1ms/step - loss: 1.8882 - accuracy: 0.5238
Epoch 7/150
11/11 [==============================] - 0s 1ms/step - loss: 1.6599 - accuracy: 0.5048
Epoch 8/150
11/11 [==============================] - 0s 2ms/step - loss: 1.4438 - accuracy: 0.4857
Epoch 9/150
11/11 [==============================] - 0s 1ms/step - loss: 1.2324 - accuracy: 0.5333
Epoch 10/150
11/11 [==============================] - 0s 1ms/step - loss: 1.0654 - accuracy: 0.5429
Epoch 11/150
11/11 [==============================] - 0s 1ms/step - loss: 0.9529 - accuracy: 0.5905
Epoch 12/150
11/11 [==============================] - 0s 1ms/step - loss: 0.8635 - accuracy: 0.7048
Epoch 13/150
11/11 [==============================] - 0s 1ms/step - loss: 0.8102 - accuracy: 0.8190
Epoch 14/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7812 - accuracy: 0.7524
Epoch 15/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7638 - accuracy: 0.6952
Epoch 16/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7525 - accuracy: 0.6762
Epoch 17/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7448 - accuracy: 0.6857
Epoch 18/150
11/11 [==============================] - 0s 2ms/step - loss: 0.7398 - accuracy: 0.6952
Epoch 19/150
11/11 [==============================] - 0s 2ms/step - loss: 0.7347 - accuracy: 0.7238
Epoch 20/150
11/11 [==============================] - 0s 2ms/step - loss: 0.7338 - accuracy: 0.6571
Epoch 21/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7278 - accuracy: 0.6762
Epoch 22/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7224 - accuracy: 0.6952
Epoch 23/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7181 - accuracy: 0.6762
Epoch 24/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7153 - accuracy: 0.6381
Epoch 25/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7097 - accuracy: 0.6762
Epoch 26/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7056 - accuracy: 0.7048
Epoch 27/150
11/11 [==============================] - 0s 1ms/step - loss: 0.7025 - accuracy: 0.6857
Epoch 28/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6969 - accuracy: 0.7143
Epoch 29/150
11/11 [==============================] - 0s 2ms/step - loss: 0.6929 - accuracy: 0.7333
Epoch 30/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6900 - accuracy: 0.7810
Epoch 31/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6871 - accuracy: 0.8095
Epoch 32/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6835 - accuracy: 0.7429
Epoch 33/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6797 - accuracy: 0.7429
Epoch 34/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6752 - accuracy: 0.6857
Epoch 35/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6696 - accuracy: 0.6762
Epoch 36/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6650 - accuracy: 0.6952
Epoch 37/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6616 - accuracy: 0.7429
Epoch 38/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6567 - accuracy: 0.7333
Epoch 39/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6532 - accuracy: 0.7429
Epoch 40/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6503 - accuracy: 0.7238
Epoch 41/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6448 - accuracy: 0.7238
Epoch 42/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6412 - accuracy: 0.7619
Epoch 43/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6371 - accuracy: 0.7619
Epoch 44/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6336 - accuracy: 0.7524
Epoch 45/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6292 - accuracy: 0.7524
Epoch 46/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6261 - accuracy: 0.7429
Epoch 47/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6231 - accuracy: 0.7333
Epoch 48/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6178 - accuracy: 0.7429
Epoch 49/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6142 - accuracy: 0.7524
Epoch 50/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6099 - accuracy: 0.7619
Epoch 51/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6083 - accuracy: 0.7524
Epoch 52/150
11/11 [==============================] - 0s 1ms/step - loss: 0.6025 - accuracy: 0.7619
Epoch 53/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5989 - accuracy: 0.7714
Epoch 54/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5968 - accuracy: 0.8381
Epoch 55/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5925 - accuracy: 0.7714
Epoch 56/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5886 - accuracy: 0.7619
Epoch 57/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5868 - accuracy: 0.7333
Epoch 58/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5811 - accuracy: 0.7810
Epoch 59/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5788 - accuracy: 0.8190
Epoch 60/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5743 - accuracy: 0.8095
Epoch 61/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5710 - accuracy: 0.8000
Epoch 62/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5675 - accuracy: 0.7810
Epoch 63/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5644 - accuracy: 0.8000
Epoch 64/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5608 - accuracy: 0.7905
Epoch 65/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5590 - accuracy: 0.7714
Epoch 66/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5541 - accuracy: 0.8190
Epoch 67/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5548 - accuracy: 0.8286
Epoch 68/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5485 - accuracy: 0.8381
Epoch 69/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5455 - accuracy: 0.8286
Epoch 70/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5420 - accuracy: 0.8381
Epoch 71/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5389 - accuracy: 0.8286
Epoch 72/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5373 - accuracy: 0.8286
Epoch 73/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5330 - accuracy: 0.8286
Epoch 74/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5301 - accuracy: 0.8286
Epoch 75/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5278 - accuracy: 0.8381
Epoch 76/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5250 - accuracy: 0.8190
Epoch 77/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5226 - accuracy: 0.8286
Epoch 78/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5185 - accuracy: 0.8190
Epoch 79/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5159 - accuracy: 0.8286
Epoch 80/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5130 - accuracy: 0.8381
Epoch 81/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5104 - accuracy: 0.8286
Epoch 82/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5071 - accuracy: 0.8571
Epoch 83/150
11/11 [==============================] - 0s 1ms/step - loss: 0.5056 - accuracy: 0.8381
Epoch 84/150
11/11 [==============================] - 0s 2ms/step - loss: 0.5024 - accuracy: 0.8476
Epoch 85/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4996 - accuracy: 0.8190
Epoch 86/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4988 - accuracy: 0.8571
Epoch 87/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4955 - accuracy: 0.8476
Epoch 88/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4921 - accuracy: 0.8381
Epoch 89/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4897 - accuracy: 0.8667
Epoch 90/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4871 - accuracy: 0.8667
Epoch 91/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4840 - accuracy: 0.8667
Epoch 92/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4818 - accuracy: 0.8571
Epoch 93/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4811 - accuracy: 0.8476
Epoch 94/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4803 - accuracy: 0.8571
Epoch 95/150
11/11 [==============================] - 0s 2ms/step - loss: 0.4751 - accuracy: 0.8762
Epoch 96/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4719 - accuracy: 0.8667
Epoch 97/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4710 - accuracy: 0.8571
Epoch 98/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4682 - accuracy: 0.8667
Epoch 99/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4668 - accuracy: 0.8667
Epoch 100/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4650 - accuracy: 0.8476
Epoch 101/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4617 - accuracy: 0.8571
Epoch 102/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4607 - accuracy: 0.8762
Epoch 103/150
11/11 [==============================] - 0s 2ms/step - loss: 0.4591 - accuracy: 0.8571
Epoch 104/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4544 - accuracy: 0.8762
Epoch 105/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4539 - accuracy: 0.8571
Epoch 106/150
11/11 [==============================] - 0s 2ms/step - loss: 0.4521 - accuracy: 0.8571
Epoch 107/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4487 - accuracy: 0.8857
Epoch 108/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4475 - accuracy: 0.8762
Epoch 109/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4451 - accuracy: 0.8857
Epoch 110/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4432 - accuracy: 0.8762
Epoch 111/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4421 - accuracy: 0.8667
Epoch 112/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4413 - accuracy: 0.8762
Epoch 113/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4372 - accuracy: 0.8762
Epoch 114/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4346 - accuracy: 0.8762
Epoch 115/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4344 - accuracy: 0.9048
Epoch 116/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4312 - accuracy: 0.8762
Epoch 117/150
11/11 [==============================] - 0s 2ms/step - loss: 0.4293 - accuracy: 0.8762
Epoch 118/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4355 - accuracy: 0.8952
Epoch 119/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4243 - accuracy: 0.9048
Epoch 120/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4248 - accuracy: 0.8762
Epoch 121/150
11/11 [==============================] - 0s 2ms/step - loss: 0.4227 - accuracy: 0.8762
Epoch 122/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8762
Epoch 123/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4180 - accuracy: 0.8857
Epoch 124/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4169 - accuracy: 0.8952
Epoch 125/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8952
Epoch 126/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4135 - accuracy: 0.8762
Epoch 127/150
11/11 [==============================] - 0s 2ms/step - loss: 0.4104 - accuracy: 0.8762
Epoch 128/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4092 - accuracy: 0.8952
Epoch 129/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4076 - accuracy: 0.9048
Epoch 130/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4060 - accuracy: 0.8952
Epoch 131/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4066 - accuracy: 0.8952
Epoch 132/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4013 - accuracy: 0.8952
Epoch 133/150
11/11 [==============================] - 0s 1ms/step - loss: 0.4005 - accuracy: 0.8762
Epoch 134/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3994 - accuracy: 0.8857
Epoch 135/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3974 - accuracy: 0.8762
Epoch 136/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3974 - accuracy: 0.8952
Epoch 137/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3951 - accuracy: 0.8952
Epoch 138/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3937 - accuracy: 0.8857
Epoch 139/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.9048
Epoch 140/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3897 - accuracy: 0.8857
Epoch 141/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3875 - accuracy: 0.8762
Epoch 142/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3861 - accuracy: 0.8762
Epoch 143/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3845 - accuracy: 0.9048
Epoch 144/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3827 - accuracy: 0.9048
Epoch 145/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3808 - accuracy: 0.9048
Epoch 146/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3800 - accuracy: 0.9048
Epoch 147/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3791 - accuracy: 0.9048
Epoch 148/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3767 - accuracy: 0.8857
Epoch 149/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3749 - accuracy: 0.8857
Epoch 150/150
11/11 [==============================] - 0s 1ms/step - loss: 0.3732 - accuracy: 0.9048
<tensorflow.python.keras.callbacks.History at 0x7fdd1fa7bfd0>
'''
pred=model.predict(x_test)
print(pred)

#find which prob is more
pred_class=np.argmax(pred,axis=1)
actual_class=np.argmax(y_test,axis=1)

from sklearn.metrics import accuracy_score
print("Accuracy of Model is:",accuracy_score(actual_class,pred_class))
#Accuracy of Model is: 0.9777777777777777






