# -*- coding: utf-8 -*-
"""Boston_Housing_LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0h2UHPJCGNA8EN8UEzHjwLhxV2gIV9G
"""

#import necessary library
import numpy as np
import pandas as pd
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import load_boston

#import data
data=load_boston()
X=data.data
Y=data.target

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.30,random_state=42)

#shape of X
X.shape

#model
model=Sequential()

model.add(Dense(13,activation='relu',input_dim=13))

model.add(Dense(13,activation='relu'))

model.add(Dense(6,activation='relu'))

model.add(Dense(1,activation='linear'))

model.compile(optimizer='Adam',loss='mean_squared_error',metrics=['accuracy'])

model.fit(x_train,y_train,epochs=1000)

model.summary()

pred=model.predict(x_test)

#model R2-value
from sklearn.metrics import r2_score
print("R-Square:",r2_score(y_test,pred))

